image: eclipse-temurin:21-jdk-jammy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - ./gradlew assemble

test_job:
  stage: test
  before_script:
    - apt-get update && apt-get install -y libgtk-3-0 libglu1-mesa libx11-6 libxfconf-0-3
  script:
    - ./gradlew test -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw