/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.yh475.battleship;

import java.io.BufferedReader;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;

/**
 * The main application class for the battle ship game
 */
public class App {
  final Player player1;
  final Player player2;

  /**
   * Construct and App instance
   * 
   * @param theBoard    is the board to manage
   * @param inputSource is where player commands are read from
   * @param out         is where message and the board view ara printed
   */
  public App(Player p1, Player p2) {
    this.player1 = p1;
    this.player2 = p2;
  }

  /**
   * The main of the Battleship applcation
   */
  public static void main(String[] arts) throws IOException {
    try {
      Board<Character> b1 = new BattleShipBoard<Character>(10, 20);
      Board<Character> b2 = new BattleShipBoard<Character>(10, 20);
      BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
      V2ShipFactory factory = new V2ShipFactory();
      Player p1 = createPlayer(input, System.out, "A", b1, factory);
      Player p2 = createPlayer(input, System.out, "B", b2, factory);
      App app = new App(p1, p2);
      app.doPlacementPhase();
      app.doAttackingPhase();
    } catch (EOFException e) {
    }

  }

  /**
   * Starts the placement phase for both players.
   * Each player will place their set of 10 ships according to the rules.
   * 
   * @throws IOException if there is an error reading input.
   */
  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException {
    while (true) {
      player1.playOneTurn(player2.getBoard(), player2.getView(), "Your Ocean",
          "Player " + player2.getName() + "'s ocean");
      if (player2.getBoard().isLost()) {
        System.out.println("Player " + player1.getName() + " win!");
        return;
      }
      player2.playOneTurn(player1.getBoard(), player1.getView(), "Your Ocean",
          "Player " + player1.getName() + "'s ocean");
      if (player1.getBoard().isLost()) {
        System.out.println("Player " + player2.getName() + " win!");
        return;
      }
    }
  }

  public static Player createPlayer(BufferedReader input, PrintStream out, String name, Board<Character> board,
      AbstractShipFactory<Character> factory) throws IOException {
    while (true) {
      out.println("Is player " + name + " a Human(H) or a Computer(C)? Please enter H or C");
      String line = input.readLine();
      if (line == null) {
        throw new EOFException("No more input");
      }
      String s = line.trim().toUpperCase();
      if (s.equals("H")) {
        return new TextPlayer(name, board, input, out, factory);
      } else if (s.equals("C")) {
        return new ComputerPlayer(name, board, out, factory);
      }
      out.println("Invalid input, please enter H for human or C for computer");

    }
  }
}
