/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.yh475.battleship;

import java.io.BufferedReader;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 * The main application class for the battle ship game
 */
public class App {
  final TextPlayer player1;
  final TextPlayer player2;

  /**
   * Construct and App instance
   * 
   * @param theBoard    is the board to manage
   * @param inputSource is where player commands are read from
   * @param out         is where message and the board view ara printed
   */
  public App(TextPlayer p1, TextPlayer p2) {
    this.player1 = p1;
    this.player2 = p2;
  }

  /**
   * The main of the Battleship applcation
   */
  public static void main(String[] arts) throws IOException {
    try {
      Board<Character> b1 = new BattleShipBoard<Character>(10, 20);
      Board<Character> b2 = new BattleShipBoard<Character>(10, 20);
      BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
      V1ShipFactory factory = new V1ShipFactory();
      TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
      TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
      App app = new App(p1, p2);
      app.doPlacementPhase();
      app.doAttackingPhase();
    }
    catch (EOFException e){
    }
    
  }

  /**
   * Starts the placement phase for both players.
   * Each player will place their set of 10 ships according to the rules.
   * 
   * @throws IOException if there is an error reading input.
   */
  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException{
    while(true){
      player1.playOneTurn(player2.theBoard, player2.view, "Your Ocean", "Player "+ player2.name+"'s ocean");
      if(player2.theBoard.isLost()){
        System.out.println("Player " + player1.name + " win!");
        break;
      }
      player2.playOneTurn(player1.theBoard, player1.view, "Your Ocean", "Player "+ player1.name+"'s ocean");
      if(player1.theBoard.isLost()){
        System.out.println("Player " + player2.name + " win!");
        break;
      }
    }

  }
}
