/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.yh475.battleship;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.StringReader;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.ResourceAccessMode;
import org.junit.jupiter.api.parallel.ResourceLock;
import  org.junit.jupiter.api.parallel.Resources;

class AppTest {
  
  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_A_wins() throws IOException {
    runTest("testA_wins_input.txt", "testA_wins_output.txt");
  }

  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_B_wins() throws IOException {
    runTest("testB_wins_input.txt", "testB_wins_output.txt");
  }

  private void runTest(String inputName, String outputName) throws IOException{
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    PrintStream out = new PrintStream(bytes, true);

    InputStream input = getClass().getClassLoader().getResourceAsStream(inputName);
    InputStream expectedStream = getClass().getClassLoader().getResourceAsStream(outputName);
    assertNotNull(input);

    InputStream oldIn = System.in;
    PrintStream oldOut = System.out;

    try{
      System.setIn(input);
      System.setOut(out);
      App.main(new String[0]);
    }
    finally{
      System.setIn(oldIn);
      System.setOut(oldOut);
    }

    String expected = new String(expectedStream.readAllBytes());
    String actual = bytes.toString();
    assertEquals(expected, actual);
  }

  
}
