/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.yh475.battleship;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.StringReader;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.ResourceAccessMode;
import org.junit.jupiter.api.parallel.ResourceLock;
import org.junit.jupiter.api.parallel.Resources;

class AppTest {

  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_B_wins_v2() throws IOException {
    runTest("test_v2_HvsH2_input.txt", "test_v2_HvsH2_output.txt");

  }

  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_ctrl_d_stop_input() throws IOException {
    runTest("empty_input.txt", "empty_output.txt");
  }

  @Disabled
  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_Computer_vs_Computer() throws IOException {
    runTest("test_v2_CvsC_input.txt", "test_v2_CvsC_output.txt");
  }

  @Disabled
  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_Computer_vs_Human() throws IOException {
    runTest("test_v2_CvsH_input.txt", "test_v2_CvsH_output.txt");
  }

  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_A_wins_v2() throws IOException {
    runTest("test_v2_input.txt", "test_v2_output.txt");

  }

  @Disabled
  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_Human_vs_Computer() throws IOException {
    runTest("test_v2_HvsC_input.txt", "test_v2_HvsC_output.txt");
  }

  // Version1 tests
  @Disabled
  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_A_wins() throws IOException {
    runTest("testA_wins_input.txt", "testA_wins_output.txt");
  }

  @Disabled
  @Test
  @ResourceLock(value = Resources.SYSTEM_OUT, mode = ResourceAccessMode.READ_WRITE)
  void test_B_wins() throws IOException {
    runTest("testB_wins_input.txt", "testB_wins_output.txt");
  }

  @Test
  void test_createPlayer() throws IOException {
    String inputData = "X\nC\nH\n";
    BufferedReader reader = new BufferedReader(new StringReader(inputData));
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    PrintStream out = new PrintStream(bytes);

    Board<Character> board = new BattleShipBoard<>(10, 20);
    V2ShipFactory factory = new V2ShipFactory();

    Player p1 = App.createPlayer(reader, out, "A", board, factory);

    assertTrue(p1 instanceof ComputerPlayer);
    String output = bytes.toString();
    assertTrue(output.contains("Invalid input, please enter H for human or C for computer"));
    Player p2 = App.createPlayer(reader, out, "B", board, factory);

    assertTrue(p2 instanceof TextPlayer);

    assertThrows(EOFException.class, () -> {
      App.createPlayer(reader, out, "C", board, factory);
    });
  }

  private void runTest(String inputName, String outputName) throws IOException {
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    PrintStream out = new PrintStream(bytes, true);

    InputStream input = getClass().getClassLoader().getResourceAsStream(inputName);
    InputStream expectedStream = getClass().getClassLoader().getResourceAsStream(outputName);
    assertNotNull(input);

    InputStream oldIn = System.in;
    PrintStream oldOut = System.out;

    try {
      System.setIn(input);
      System.setOut(out);
      App.main(new String[0]);
    } finally {
      System.setIn(oldIn);
      System.setOut(oldOut);
    }

    String expected = new String(expectedStream.readAllBytes());
    String actual = bytes.toString();
    assertEquals(expected, actual);
  }

}
